/**
 * Action types
 */
const FETCH_USER = 'FETCH_USER';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

const FETCH_PERSONAL_INFO = 'FETCH_PERSONAL_INFO';
const FETCH_PERSONAL_INFO_SUCCESS = 'FETCH_PERSONAL_INFO_SUCCESS';
const FETCH_PERSONAL_INFO_ERROR = 'FETCH_PERSONAL_INFO_ERROR';

const RESET_USER  = 'RESET_USER  ';


export const constants = {
  FETCH_USER,
  FETCH_USER_SUCCESS,
  FETCH_USER_ERROR,
  FETCH_PERSONAL_INFO,
  FETCH_PERSONAL_INFO_SUCCESS,
  FETCH_PERSONAL_INFO_ERROR,
  RESET_USER ,
};